### ISSUE TITLE
Implementation Guides for Open Gambia v0.1

### ISSUE THREAD

**Issue by viraj89** [beckn/missions#103]
## Description
Now that a template starter kit and implementation guide structure have been decided, the following steps will be taken:

1. The Missions team will create and maintain the implementation guide for each mission, including **Open Gambia**.
2. The implementation guide will be stored in the designated repository.
3. The only external input for the implementation guide will be the outcome visualization provided by the Program Management team.
4. The implementation guide will consist of the following sections:
   a. Outcome visualization (provided by the Program Management team)
   b. Flow diagram
   c. API details
   d. Taxonomy and any Layer 2 rules
   e. General instructions for Seeker and Provider Platform implementers (mostly common across missions)
   f. Attachments (Postman collection and Layer 2 configuration file)

Following this approach, create the implementation guide for the **Open Gambia** project and share it on the Confluence Page [here](https://fide-official.atlassian.net/wiki/spaces/TPP/pages/398721035/Open+Gambia). 

## Goals
- [ ] Develop and maintain the **Open Gambia** implementation guide.
- [ ] Ensure all necessary sections are included and documented.
- [ ] Store the implementation guide in the specified repository.

## Expected Outcome
- A comprehensive **Open Gambia** implementation guide is created and stored in the repository.
- The guide includes all required sections and is ready for use by mission teams and implementers.

## Acceptance Criteria
- [ ] The implementation guide includes outcome visualization, flow diagram, API details, taxonomy, Layer 2 rules, and general instructions.
- [ ] Attachments (Postman collection and Layer 2 configuration file) are included.
- [ ] The implementation guide is reviewed and approved by relevant stakeholders.

## Mockups / Wireframes
N/A

## Product Name
Beckn Open Gambia

## Domain
e-comm

## Tech Skills Needed
Documentation, API Design, Process Flow

## Complexity
High

## Category
Documentation

## Sub Category
Implementation Guide

**Comment by ankitShogun** [comment]
Received [this](https://fide-official.atlassian.net/wiki/spaces/TPP/pages/389283844/Phase+2+-+Open+Belem) open gambia documentation from @meenakshi2468 on Wednesday (11 Sep 2024) . Following this for context

**Comment by ankitShogun** [comment]
Updating the postman collection since older one is outdated

**Comment by ankitShogun** [comment]
Updated the postman collection and made some fixes in the guide https://github.com/beckn/missions/pull/187
