### ISSUE TITLE
Upgrade Open Amsterdam Project to Beckn Protocol 1.1 and ONIX Compliance

### ISSUE THREAD

**Issue by viraj89** [beckn/missions#104]
## Description
The Open Amsterdam project previously utilized Beckn protocol v0.9, developed by the Automicle team, which set up buyer and seller apps for local businesses in Amsterdam. Two BPPs were used:
1. A Shopify adapter developed by Venky Mahadevan.
2. A BPP developed by the Plotch team.

The BAP was forked from FIDE's 0.93 version of Open Ams and modified for payment functionalities. The project has ended, and now, with the introduction of Beckn-ONIX, the Open Amsterdam project requires an upgrade to Beckn Protocol 1.1 and compliance with ONIX.

The next steps involve checking with the Automicle team to understand:
- The current status of the project.
- Whether any new buyers or sellers have been onboarded.
- The Automicle team's readiness for utilizing the new Vendure BPP.
- The necessity to upgrade the BAP due to the earlier version utilized.

A starter kit for Beckn-ONIX has been shared with the Automicle team to facilitate the upgrade process.

## Goals
- [ ] Conduct a status check with the Automicle team to understand the current state of the Open Amsterdam project.
- [ ] Confirm if any new buyers or sellers have been onboarded since the project ended.
- [ ] Assess Automicle’s readiness to utilize the new Vendure BPP in place of the earlier BPPs.
- [ ] Plan for upgrading the BAP to be compliant with Beckn Protocol 1.1 and ONIX.

## Expected Outcome
- A clear understanding of the current status of the Open Amsterdam project.
- A plan for upgrading the BPP to Vendure BPP and ensuring BAP is upgraded to Beckn Protocol 1.1.
- Confirmation of whether new buyers or sellers have been onboarded and Automicle’s readiness to proceed with the upgrades.

## Acceptance Criteria
- [ ] The current status of the project is confirmed with the Automicle team.
- [ ] Confirmation of whether any new buyers or sellers were onboarded.
- [ ] The Automicle team’s readiness to integrate the new Vendure BPP is assessed.
- [ ] BAP upgrade requirements are defined and the next steps planned for the upgrade.

## Mockups / Wireframes
NA

## Product Name
Open Amsterdam

## Domain
Local Commerce Infrastructure

## Tech Skills Needed
- Beckn Protocol (v0.9 and v1.1)
- BPP/BAP Knowledge
- Shopify Adapter and Vendure BPP Integration
- Beckn-ONIX Compliance

## Complexity
High

## Category
Project Upgradation

## Sub Category
BPP/BAP Upgrade

## Project View
Open Amsterdam Project

## Project Name
Open Amsterdam

**Comment by yesrag2309** [comment]
Viraj will be connecting with Sindhuja on the details. Meeting TBD.

@viraj89 @emmayank @faizmagic

**Comment by viraj89** [comment]
On Sept 12, 2024, a meeting was held with Bharath, @viraj89, and @yesrag2309 for the Open Amsterdam project. Based on the requirements from Bharath, it is understood that the Open Amsterdam team requires the following support from FIDE:
1.	Share the starter kit with the Open Amsterdam team.
2.	Provide handholding for enabling the Open Amsterdam project to upgrade to protocol server 1.1.
3.	Ensure the Open Amsterdam project is Beckn ONIX compliant.
4.	Any fixes beyond this from FIDE are not part of the current scope.
A call with the Open Amsterdam team will be arranged once they have reviewed the starter kit, to provide technical support as needed.

cc @faizmagic @yesrag2309 @bharath-ganapathy

**Comment by viraj89** [comment]
status and next steps:

**Comment by viraj89** [comment]
#### Update: Oct 28, 2024
No update from Automicle team for the week of Oct 21-25 after the previous update, communicated to the team about the same via email. Proof below. 

The following email was sent to the team stating there is no update or response from the Automicle team, this flow is de-priotized. 

Closing this ticket for now. 

![Image](https://github.com/user-attachments/assets/327ca347-250c-4868-80d4-9a44b4c6289e)
