### ISSUE TITLE
Win Room Planning

### ISSUE THREAD

**Issue by harshcrop** [beckn/missions#105]
On Aug 19-30 iteration Harsh has completed the below items. Since the iteration is ended up and there are some tasks to taken care. I am closing this card and in the current iteration Sep 2-15 #105 new is card created for tracking.

Completed Details

Beckn Onix Hackathon

Date: 26,27,28 Spt 2024

Location:

Time:

Email Template for TSP ID [link](https://docs.google.com/document/d/1qRuNvsuyb8QZmgXgggAa-FrcdQRY6zN0fG2YhGoISM8/edit#heading=h.tdh2odhdz6ga)

Hackathon doc [link] (https://docs.google.com/document/d/1li7UAkBrhCI3RFZuC_Xg2sRFuOB1bOnwyxomOfnkgRg/edit#heading=h.4qwbkxdh1n55)

Pending Details

- [ Need to send TSPs after new template is approved by Ravi ]
- [ Connect NPs for Win Room ]
- [Connect Dhiraj for asking lumpsum budget info]
- [send email to Sujit for FIDE event budget discussion ]

**Comment by harshcrop** [comment]
Update 6 Spt

We are changing the Email Template based on Ravi's suggestion, and we are changing the name of the hackathon to Win Room from now on.

- [ Need to send TSPs after new template is approved by Ravi ]
- [ Connect NPs for Win Room ]
- [Connect Dhiraj for asking lumpsum budget info]
- [send email to Sujit for FIDE event budget discussion ]

**Comment by harshcrop** [comment]
Spt 10 

[ Need to send TSPs after new template is approved by Ravi ]
[ Connect NPs for Win Room ]
[Connect Dhiraj for asking lumpsum budget info]
[send email to Sujit for FIDE event budget discussion ]

This tasks are done

**Comment by yesrag2309** [comment]
@harshcrop - Please update the current status of this card. You posted an update on 123th Sep in comment #102. Kindly update the comment here, as this is the active working card.

@viraj89 @faizmagic

**Comment by yesrag2309** [comment]
As discussed in today's sync-up call with @harshcrop, please find the updates below:

1. The date and venue have been finalized: 21st October 2024 at the FIDE office in Bangalore.
2. @SyedMubarak008 will share the first draft of the Masterclass PPT for review with @ravi-prakash-v on 23rd September 2024.
3. @harshcrop is working with @SyedMubarak008 on the structure/mock screens for the WIN Room event website. Mock screen review is being planned with @ravi-prakash-v tentatively by early next week.
4. In parallel, @harshcrop is working on the event plan, with a review scheduled with @ravi-prakash-v on 23rd September 2024.

@viraj89 @emmayank @faizmagic

**Comment by yesrag2309** [comment]
@harshcrop has shared the Win Room & Demo Agenda to @ravi-prakash-v  for review.

Based on @SyedMubarak008 completion @harshcrop will be sharing the master class PPT to Ravi by today EOD.

@viraj89 @emmayank @faizmagic

**Comment by harshcrop** [comment]
Update

PPT is shared by @SyedMubarak008 

Event Page is live now - https://lu.ma/bl03a20b

New Invite mail draft - https://docs.google.com/document/d/1W1AEP571hY8tva1leuz3NkPFi5pAsnBFY8WXGpAdekM/edit?usp=sharing
