### ISSUE TITLE
Create detailed test case list for the Beckn-ONIX spec

### ISSUE THREAD

**Issue by vbabuEM** [beckn/missions#111]
## Description

The Beckn-ONIX core requirements spec is being published. Write a detailed test case document that addresses each requirement of the Beckn-ONIX core requirements spec.

cc @faizmagic

**Comment by vbabuEM** [comment]
The test guide document is stored here https://fide-official.atlassian.net/wiki/x/F4AxIw
This will have to be updated for all modifications to the original spec as and when it happens.

**Comment by yesrag2309** [comment]
Test Guide Document is created. Hence closing this card. 

Based on the original spec post review changes the test guide will get update . Hence closing this card. 

Test guide update is tracking under #128  card in Sep16-29 iteration.

@vbabuEM @viraj89 @faizmagic
