### ISSUE TITLE
Helping Swayangjit from discord community to debug onix related issues

### ISSUE THREAD

**Issue by ankitShogun** [beckn/missions#112]
Swayangjit contacted both me and Venkatesh on several discord channels regarding problems he was facing in setting up beckn architecture on this system. Mostly using beckn-onix. Need to help him debug and solve whatever problems he is facing.

**Comment by ankitShogun** [comment]
1. The primary problem was that any protocol server could not connect to the registry internally. Solutions revolved around changing config files for each protocol server manually. Found a loophole in the beckn-onix config also

**Comment by ankitShogun** [comment]
[This](https://discord.com/channels/933320455903907840/1280416034381234217) is the ongoing discord thread. Helping him with more of his issues.

**Comment by emmayank** [comment]
Review Completed

@ankitShogun as discussed, please use office hours only to debug issues faced by participants, also for any specific issues, ask them to create a issue ticket with proper description and screenshot, so that you can pick it up in the current/next iteration based on the priority
