### ISSUE TITLE
Starter Kit Google Doc Creation and Formatting Fixes

### ISSUE THREAD

**Issue by viraj89** [beckn/missions#114]
## Description
The starter kit found [here](https://github.com/beckn/missions/blob/main/docs/starter_kit/starter_kit.md) needs to be transferred to a Google Doc. The following tasks are to be completed:

- Transfer the entire starter kit from the repository to a Google Doc.
- Fix the formatting issues such as spacing, numbering, headers, font size, and placing single blocks inside table cells or code blocks.
- Ensure that the table of contents is properly formatted.

Once completed, share the Google Doc link and send an email to Faiz.

## Goals
- [ ] Transfer the starter kit content to a Google Doc.
- [ ] Fix all formatting issues.
- [ ] Share the document link and email Faiz.

## Expected Outcome
A well-formatted Google Doc version of the starter kit with correct spacing, numbering, headers, font size, table of contents, and code block placement.

## Acceptance Criteria
- [ ] Starter kit content transferred to Google Doc.
- [ ] All formatting issues resolved.
- [ ] Link shared and email sent to Faiz.

## Product Name
Beckn Missions

## Category
Documentation

## Sub Category
Formatting

**Comment by viraj89** [comment]
https://docs.google.com/document/d/1nfQUM4blkng1VDWXTWirCc544jx8SOQIZ5rZUtju3VQ/edit#heading=h.vnsj023p23mm

**Comment by viraj89** [comment]
This is done and shared over email to Faiz on Sept 9. Hence marking this ticket as closed. 
Google Doc link is [here](https://docs.google.com/document/d/1nfQUM4blkng1VDWXTWirCc544jx8SOQIZ5rZUtju3VQ/edit#heading=h.vnsj023p23mm).

**Comment by yesrag2309** [comment]
Beckn Starter guide is created and sent review to Ravi. Hence closing this card. Review and Rework is tracking under #129  card in Sep16-29 iteration.

@vbabuEM @viraj89 @faizmagic
