### ISSUE TITLE
Beckn Starter Kit V3.0 Document Review & Rework

### ISSUE THREAD

**Issue by yesrag2309** [beckn/missions#129]
## Back Story

Beckn Starter guide is created and sent review to Ravi. Hence closing this card. Review and Rework is tracking under this  card in Sep16-29 iteration.

## Reference Card
#114

**Comment by viraj89** [comment]
#### Starter Guide Link - 
Google Doc link is [here](https://docs.google.com/document/d/1nfQUM4blkng1VDWXTWirCc544jx8SOQIZ5rZUtju3VQ/edit#heading=h.vnsj023p23mm).
