### ISSUE TITLE
KT session for Avil Awate for the missions role

### ISSUE THREAD

**Issue by meenakshi2468** [beckn/missions#138]
New member joined the EM team as replacement for Venkatesh. KT sessions for Beckn enablement planned as below:

**Session 1**

Brief overview of Beckn
Details about the 10 endpoints

**Session 2**

A hands-on on how to build example JSONs for 2 or 3 use cases for both request and responses

**Session 3**

End-to-end Postman collection execution on various use cases
Introduction to various Beckn assets and provide links to tutorials and README

**Session 4**
End to End Beckn-ONIX deployment

**Comment by Kathirvel-ai** [comment]
To be completed by Wednesday (9 Oct)

**Comment by rajaneeshk90** [comment]
Started the first session today with [this](https://mindsenterprise-my.sharepoint.com/personal/ninad_shenoy_eminds_ai/_layouts/15/onedrive.aspx?id=%2Fpersonal%2Fninad%5Fshenoy%5Feminds%5Fai%2FDocuments%2FAttachments%2FBeckn%20Protocol%20%2D%20Tech%20Overview%2Epdf&parent=%2Fpersonal%2Fninad%5Fshenoy%5Feminds%5Fai%2FDocuments%2FAttachments&ct=1728377140990&or=OWA%2DNT%2DMail&cid=e9272a45%2Dbba0%2Ddf3b%2Db38e%2D12249dd0b65f&ga=1) document as reference.

We covered basics of Beckn. He had to pause the session in middle as he got a call to join another session.

Could not reach out to him to resume the session later.
