### ISSUE TITLE
UEI: Updates in the implementation guide, updates in the L2 config

### ISSUE THREAD

**Issue by faizmagic** [beckn/missions#159]
**Description**

1. Update the existing UEI L2 config https://github.com/beckn/missions/tree/main/UEI/layer2, based on the changes to the implementation guide
2. Make the L2 config strict.
3.  Upload the L2 config to the missions repo
      https://github.com/beckn/missions/tree/main/UEI/layer2

**Comment by yesrag2309** [comment]
**Current Status**

1. Based on @faizmagic review comments we had a connect with Pooja on enums & standardize the tag codes. Based  on that call outcome @rajaneeshk90 has to connect with NPs
2. Based on @faizmagic  suggestion on L2 Config @rajaneeshk90 is working on the L2 cofig file make it as strict that NPs couldn't customize. ETA 14th Nov.

**Next Steps**

1. Need to update the Guide 1.1 and L2 config file based on @faizmagic comments
2. Additional NP point has to incorporate in the guide under V 1.2 by next week.
      - [ ] For reference additional points details, An additional point was raised regarding charging options. Some NPs prefer time-based 
        charging, while others prefer energy unit-based or money-based charging. We should add examples demonstrating each of these 
        options

**Comment by yesrag2309** [comment]
## NPs Feeback/Changes [to be incorporated into the implementation guide Ver1.1]

1. **Charging Point Details:** Add charging point details in the catalog. Information related to charging connectors already exists, and this should be added to the fulfillments object.

2. **Charging Station Details:** Add charging station information to the catalog. (A charging station can have multiple charging points, and each charging point can have multiple connectors.) This should be included in the provider description and location sections.

3. **Quotation Object:** Remove the quotation object from the confirm API payload. Update the quotation object in the on_select, on_init, on_confirm etc.

4. **Current Charging Details:** Add details related to the current charging status—such as state of charge, energy delivered, current voltage, etc.—in the on_status payload. This should be included within the fulfillments tags.

## Internal Review Comments

1. L2 cofig file make it as strict that NPs couldn't customize
2. The tag descriptions for UEI should be included in the implementation guide, with each tag defined by SN, name, code, meaning, and usage. This table will evolve based on NP inputs.

**Current Status**

1. Based on @faizmagic  suggestion on L2 Config @rajaneeshk90 is working on the L2 config file make it as strict that NPs couldn't customize. ETA 18th Nov.
2. Based on @faizmagic review on 12th November. The tag descriptions for UEI should be included in the implementation guide, with each tag defined by SN, name, code, meaning, and usage. This table will evolve based on NP inputs.
3. The above mentioned NPs suggested feedback/changes are updated and it will be published as Ver1.1 along with the preparing L2 config file ETA 18th November


**Next Steps**

## Version 1.1

1. The above mentioned @faizmagic review comments to be update and it will be published as Ver1.1 along with the L2 config file ETA 18th November

## Version 1.2
1. Additional NP point has to incorporate in the guide under V 1.2 by 22nd Nov
      - For reference additional points details, An additional point was raised regarding charging options. Some NPs prefer time-based 
        charging, while others prefer energy unit-based or money-based charging. We should add examples demonstrating each of these 
        options
2. We need to merge the Fulfillment Objects Connector Spec and Charging Point Spec. The tech team will have a call with the NPs and @poojamanjooran  to explain that this approach is better. If the NPs agree, the changes will be implemented, and we will publish version 1.2 on 22nd Nov

**Comment by yesrag2309** [comment]
## Current Status

**Version 1.1** - ETA 18th Nov

1. @rajaneeshk90 has completed the L2 configuration file, setting it to be strict, which prevents NPs from customizing it.
2. We had a check-in call with NPs.
3. Following today’s NPs check-in call, tag descriptions are being prepared by NPs, with each tag defined by SN, name, code, meaning, and usage. Once finalized, @rajaneeshk90 will incorporate these into the implementation guide as a table. This table will be dynamic, allowing NPs to update it as tags are added or modified.

**Version 1.2** - ETA 22nd Nov

1. We had a check-in call with NPs.
2. Following today’s NP check-in call, @rajaneeshk90 will share an example JSON demonstrating the merging of the Fulfillment Objects Connector Spec and Charging Point Spec in the Discord channel. NPs can review this example, and once it is reviewed and approved, it will be included in the guide as part of version V1.2.

## Next Steps

**Version 1.1** - ETA 18th Nov

1. Following today’s NP check-in call, tag descriptions are being prepared by NPs, with each tag defined by SN, name, code, meaning, and usage. Once finalized, @rajaneeshk90 will incorporate these into the implementation guide as a table. This table will be dynamic, allowing NPs to update it as tags are added or modified.

**Version 1.2** - ETA 22nd Nov

1. Additional NP point has to incorporate in the guide under V 1.2 by 22nd Nov
      - For reference additional points details, An additional point was raised regarding charging options. Some NPs prefer time-based 
        charging, while others prefer energy unit-based or money-based charging. We should add examples demonstrating each of these 
        options
2. Following today’s NP check-in call, @rajaneeshk90 will share an example JSON demonstrating the merging of the Fulfillment Objects Connector Spec and Charging Point Spec in the Discord channel. NPs can review this example, and once it is reviewed and approved, it will be included in the guide as part of version V1.2.


CC- @faizmagic @poojamanjooran @viraj89 @emmayank

**Comment by yesrag2309** [comment]
**Current Status**

1. Working on tag descriptions which is prepared by NPs, with each tag defined by SN, name, code, meaning, and usage. Incorporating these into the implementation guide as a table. This table will be dynamic, allowing NPs to update it as tags are added or modified.
2. Working on the example JSON demonstrating moving the Fulfillment Object Connector Specification from fulfillment array into items[idx] and share in the Discord channel. NPs can review this example, and once it is reviewed and approved, it will be included in the guide as part of version V1.2
3. Working on add meta APIs (e.g., get_rating_categories) and other relevant details in the implementation guide.

**Next Steps**

**Version 1.2 - ETA 22nd Nov**

1. Additional NP point has to incorporate in the guide under V 1.2 by 22nd Nov
      - For reference additional points details, An additional point was raised regarding charging options. Some NPs prefer time-based charging, while others prefer energy unit-based or money-based charging. We should add examples demonstrating each of these options.
      
 CC- @faizmagic @poojamanjooran @viraj89 @emmayank

**Comment by yesrag2309** [comment]
Based on the @faizmagic review comments, we have completed the L2 configuration file, setting it to be strict, which prevents NPs from customizing it. Layer 2 file link - [Click Here](https://github.com/beckn/missions/tree/main/UEI/layer2). Hence we can close this flow card.

@rajaneeshk90 @viraj89 @emmayank
