### ISSUE TITLE
UAI: Implementation Guide Version 0.1 L2 Config

### ISSUE THREAD

**Issue by faizmagic** [beckn/missions#160]

**Comment by yesrag2309** [comment]
**Current Status**

1. UAI implementation guide MD files Ver0.1 are shared to Global Mission Team for Advisory, Rental & Sales use cases.
2. Internal review with @faizmagic is scheduled on 12th Nov 4-5.30pm
3. L2 config file is InProgress Advisory use case ETA by 12th Nov EOD & Rental & Sales use cases ETA 14th Nov EOD

**Next Steps**

1. Once @faizmagic review is completed and if there is any review comments need to incorporate and share the Ver 1.0 to Global Mission Team.
2. Once L2 files are prepared need to share it with Global Mission Team.

@rajaneeshk90

**Comment by yesrag2309** [comment]
## Internal review comments

**Incorporated in V0.1**

1. Add cancellation_terms and other relevant details in the on_init payload.
2. Replace technical terms related to crop diseases with simpler, layman-friendly names (e.g., change "Stemphylium leaf blight" to "Kala Daag").
3. The current implementation assumes that the BPP collects the payment. This should be updated to reflect that the BAP is responsible for collecting the payment.
4. Change the example "bap_id": "ps-bap-network.becknprotocol.io" to something like example.becknprotocol.io and add a comment in the implementation guide to clarify that it's just an example for the NPs.

**Pending to Incorporate in V0.2**

## Current Status

1. The above internal review comments are incorporated in the implementation guide as part of V0.1
2. L2 Config file prepared for Rental Use case
3. Tech team participated in the Master Class session today and showcased the Implementation Guide for Advisory, Rental & Sales along with Advisory, Rental L2 config file

## Next Steps

1. L2 config for Sales use case will be ready by 14th Nov EOD.
2. The below version 0.2 review comments need to discuss with @Kathirvel-ai and tech team will try incorporate before 19th Winroom.

## Version 0.2

1. Need to check with @Kathirvel-ai how the paid advisory forecast data is delivered. What is the use case for the NPs?
2. Based on the paid advisory discussion the BPP flow needs to update.

@rajaneeshk90 @viraj89 @emmayank @faizmagic

**Comment by yesrag2309** [comment]
**Current Status**

1. Working on add meta APIs (e.g., get_rating_categories) and other relevant details in the implementation guide.

**Next Steps**

1. L2 config for Sales use case will be ready by 18th Nov EOD.
2. The below version 0.2 review comments need to discuss with @Kathirvel-ai and tech team will try incorporate before 19th Winroom.

**Version 0.2**

1. Need to check with @Kathirvel-ai how the paid advisory forecast data is delivered. What is the use case for the NPs?
2. Based on the paid advisory discussion the BPP flow needs to update.

@rajaneeshk90 @viraj89 @emmayank @faizmagic

**Comment by yesrag2309** [comment]
L2 config files are prepared and published in the UAI Mission Repo. Hence closing this flow. For reference, L2 config file link - [Click Here](https://github.com/beckn/missions/tree/main/UAI/layer2)

@faizmagic @rajaneeshk90 @viraj89 @emmayank
