### ISSUE TITLE
UAI-Support eNAM & Carnot with the implementation process

### ISSUE THREAD

**Issue by yesrag2309** [beckn/missions#181]
## Description

Following the UAI Winroom outcome, eNAM & Carnot is seeking support for the implementation process. @Kathirvel-ai will confirm the date and time for the NPs call by the end of today (25th Nov). Tentatively, the call is scheduled for either the 27th or 28th of November and will last 4–5 hours.

**Comment by yesrag2309** [comment]
@ankitShogun - Following the UAI Winroom outcome, eNAM is seeking support for the implementation process. @Kathirvel-ai will confirm the date and time for the NPs call by the end of today (25th Nov). Tentatively, the call is scheduled for either the 27th or 28th of November and will last 4–5 hours.

@faizmagic @viraj89 @emmayank @Kathirvel-ai

**Comment by yesrag2309** [comment]
@Kathirvel-ai - Kindly let tech team know on the support details.

@faizmagic @viraj89 @emmayank

**Comment by Kathirvel-ai** [comment]
@yesrag2309 @faizmagic @emmayank @viraj89 

We can have a shorter format of winroom on Thursday from 2 PM to 5 PM and Friday from 2 PM to 5 PM

**Comment by yesrag2309** [comment]
As discussed with @Kathirvel-ai Ankit is primarily required for the above mentioned 2 days support. In case of any blockers he need Prasad and Shrey support in that connect. @viraj89 please set the expectations with them and kindly do the needful.

@faizmagic @emmayank

**Comment by Kathirvel-ai** [comment]
UAI winroom support was provided by Prasad and Bhanu. Shrey assisted on a case to case basis.

Outcome:
Carnot (equipment rental BPP) - completed the beckn-ONIX setup, pending integration testing
eNAM (price discovery BPP) - beckn-ONIX setup and search request was completed. dropped midway to realign with their team internally and get back.
