### ISSUE TITLE
UAI Implementation Guide update

### ISSUE THREAD

**Issue by Kathirvel-ai** [beckn/missions#199]
## Description

The UAI implementation guide has use cases such as
1) Advisory
2) Equipment Rental
3) Equipment Sales
Post the winroom the participants wanted to updated their search API with certain input parameters

Please find the link to the implementation guide [here](https://github.com/beckn/missions/blob/main/UAI/implementation_guide_knowledge_advisory.md)
Please find the link to the input parameters [here](https://docs.google.com/spreadsheets/d/1mm86xg91LupdG8tOfFlWDdvD8LYw3-UECzg24CRxICM/edit?gid=0#gid=0)

Need to update the search APIs with the input details shared above, so that similar format is used by all the participants.

Note Advisory use case has sub categories - Weather Advisory, Spray Schedule Advisory, Pest and Disease Advisory, Price Discovery, Schemes

## Goals

- [x] Update Advisory Use Case (search API) - Price discovery, Weather Data, Spray Schedule, Pest and Disease Advisory with the input details
- [x] Update Equipment Rental Use Case (search API) - with the input details

**Comment by rajaneeshk90** [comment]
The changes were made as part of the following changes

1. https://github.com/beckn/missions/commit/9d216690f2a63e1683af0f8aedac5515fe63bece
2. https://github.com/beckn/missions/commit/a589e8c56daed2808f3c1aed996e62661be8695e
