### ISSUE TITLE
UPPCL Implementation Guide V1.0

### ISSUE THREAD

**Issue by yesrag2309** [beckn/missions#204]
## UPPCL: Mission Support
**Description**
Online Winroom session is planned on 7th-8th Jan 2025.
FIDE Spec team is working on the spec and implementation guide document and it will be available by 20th December 2024.
**Next Steps** 
FIDE engineering team needs to support the missions team on the winroom session and sandbox development.
Online Winroom session is planned on 7th-8th Jan 2025.

**Associated Tickets:**
https://github.com/beckn/missions/issues/186

**Comment by yesrag2309** [comment]
@rajaneeshk90 - Please update the current status on the implementation guide here. ETA for implementation guide is 20th Dec.

@faizmagic @emmayank @viraj89

**Comment by rajaneeshk90** [comment]
Needed outcome visualisation for the Implementation guide.

Had a call with Meenakshi to communicate this requirement.

This is the outcome visualisation document i received from Meenakshi: https://docs.google.com/document/d/1HD8fw9dCvqWoPXFwPuOPiZCOw3WOBqWpAjY6Vi5RWdM/edit?tab=t.0

reviewed this, provided some comments.

**Comment by rajaneeshk90** [comment]
Created an incomplete initial draft of the implementation guide in a separate branch of the missions git repo: https://github.com/beckn/missions/blob/uppcl-implementation-guide/UEI/implementation_guide_P2P_energy_trade.md

**Comment by rajaneeshk90** [comment]
Updated the implementation guide accordingly: https://github.com/beckn/missions/tree/uppcl-implementation-guide

Implementation guide is not compete yet.

**Comment by rajaneeshk90** [comment]
Had added the following in the implementation guide in last 2 days:

1. Added the Observability Layer flow.
2. Added Observability Layer example JSONs.
3. Added a section on how the integrity of the Order objects getting saved on the observability layer can be verified.
4. Added status on_status examples.
5. Discussions of the changes needed in the outcome visualisation and getting it finalised with the help of Meenakshi.
6. reflect the changes in the outcome visualisation and images into the implementation guide.

**Comment by rajaneeshk90** [comment]
The draft version of the implementation guide was reviewed by Ravi yesterday, he suggested some architectural changes. 
I am creating a short document on the proposed architecture. Dr Pramod is expected to review those changes before we incorporate them into the implementation guide.

There are major changes in comparison to the previous discussions.

**Comment by rajaneeshk90** [comment]
The new document that was created for the observability layer based on Ravi's feedback: https://docs.google.com/document/d/1_4rD_WF4hsvuo6U1JqOQcy7PvRgPJFMfZ0rCPji0wv0/edit?tab=t.0#heading=h.3c0hhi4ek16a

**Comment by rajaneeshk90** [comment]
There is another discussion as per which the Observability Layer might not be needed at all. Haven't looked into it yet.

**Comment by rajaneeshk90** [comment]
This ticket will be closed as the iteration is over. future work will be done as part of a new ticket. 

will link the ticket here once it is created.
