### ISSUE TITLE
Create generic starter kit

### ISSUE THREAD

**Issue by vbabuEM** [beckn/missions#45]
## Description
Create a network agnostic starter kit.  that covers the following Table contents

The details of the TOC are available in the below google docs
https://docs.google.com/document/d/1iskX94fdpklw-d-lSUbvVuoyFeIVQwDK55PuJ_LKMsM/edit

Please refer the google docs to prepare the starter kit

**Comment by vbabuEM** [comment]
https://github.com/beckn/missions/blob/main/starter_kit/starter_kit.md

**Comment by faizmagic** [comment]
@vbabuEM Re-opening this flow based on the review comments received from the global missions team.

**Comment by vbabuEM** [comment]
There is a complete new structure we are working on. I think this issue can be closed. @faizmagic , your call.

**Comment by faizmagic** [comment]
@vbabuEM , we can close it, if you have opened a new ticket, please copy all of these information on to the new ticket.

**Comment by vbabuEM** [comment]
The entire starter kit contents has been reimagined to cater to the comments above. The new work is captured in 
https://github.com/beckn/missions/issues/58
https://github.com/beckn/missions/issues/59
https://github.com/beckn/missions/issues/60
https://github.com/beckn/missions/issues/61
