### ISSUE TITLE
Create FAQ for Beckn Assets - V1.0

### ISSUE THREAD

**Issue by faizmagic** [beckn/missions#6]
## Description

FIDE is conducting a daily tech office hours session for the community, please join the meeting and create a FAQ document based on the questions asked by the community and the NP's.

we had 2 office hours which happened on 23rd July and 15th July. i am attaching both the recording. Please go through the recording's and create an beckn FAQ document in confluence for now, we will publish it as a public document once we have sizeable content.

confluence link: https://fide-official.atlassian.net/wiki/spaces/TPP/pages/510754836/Beckn+FAQ+s

July 15th Recording: https://drive.google.com/file/d/17WmDlQAkL4-IO2TjzzOUcffx9Zg0jfYp/view
July 22nd Recording: https://drive.google.com/file/d/14M0El-15d-BR7s4pW0aHmjtqPb58BlL0/view
July 24 Recording: https://drive.google.com/file/d/1CKLioqHreieX5BbJT7TgCAS6fIiVWeFJ/view?usp=drive_open

## Expected Outcome

- [ ] Create FAQ and document the same in confluence for the following products / spec
1. Registry
2. Gateway
3. Protocol Server
4. Beckn Specification
5. Beckn ONIX

- [ ] This will be a living document and needs to be updated based on the questions from the community

## Acceptance Criteria

- [ ] Ensure all know questions are captured 
- [ ] Ensure all questions from the community across github and discord are captured

## Implementation Details
NA

---

[Please note that the below section of the ticket ****has to be in the format as mentioned as it is key to enabling proper listing of the project.**** Please only choose the options mentioned under the headings wherever applicable.]

### Product Name
1. Registry
2. Gateway
3. Protocol Server
4. Beckn Specification
5. Beckn ONIX

**Comment by faizmagic** [comment]
Adding the link to the BOSCH  Q&A doc https://docs.google.com/document/d/1QwUQIBuUaRpQqQRp46KfUCIkK6kxr1W3/edit

Please add these as well to the FAQ

CC: @ankitShogun

**Comment by faizmagic** [comment]
@ankitShogun , Added the July 24th recoding to the issue description.

CC: @vbabuEM

**Comment by ankitShogun** [comment]
Added all the faqs possible. Please review and close @faizmagic

**Comment by ankitShogun** [comment]
Connected with devansh on the same. Will updated the faqs once I receive all the queries from his side.

**Comment by ankitShogun** [comment]
Still waiting for devansh reply

**Comment by emmayank** [comment]
@ankitShogun  please list all the questions you will be answering and then update the estimate accordingly. for now i have made it to 4 hrs as per @faizmagic

**Comment by viraj89** [comment]
The version 1.0 updates are documented here on this link - https://github.com/beckn/missions/blob/main/docs/faq.md

The subsequent updates to the v2.0 will be done in the next iteration starting Aug 19, hence closing this ticket.
