### ISSUE TITLE
Create Starter Kit

### ISSUE THREAD

**Issue by faizmagic** [beckn/missions#7]
## Description

Create a generic starter kit that can be utilised by global programs team across missions  and document the same in confluence. Please utilise ONEST starter pack as a reference

https://starterpack.onest.network/

TOC to be covered
1. Introduction & Roles you can play - Mission specific
     a. Focus Areas
     b. Core Principles
     d. Roles you can Play
2. NP Go-Live Checklist
3. Onboarding Sandbox Registration
    a. Seeker Registration
    b. Provider Registration
4. Network Observability - We will add this information once this is established
    a. Introduction
    b. Telemetry Implementation
    c. Dashboard Details

LEARN
 1. Beckn Protocol - Video Library
 2. Getting Started - Mission Specific, content will be generated from the Master Class
 3. Understanding the API's  - same content to be fine tuned based on mission
 4. Beckn Implementation
     a. Getting Started
          i. _introduction
          ii. explain about the various assets available 
          iii. provide details of the assets, hardware / infra requirements
          iv. setup / deployment details_
      b. Implementation
            i. _Outcome Visualisation
            ii. Implementation Guide
                  a. Provide details of the API' which needs to be implemented along with flow diagrams
                  b. example jsons
                  c. Schema Field Definitions and Enums
                  d. Mandatory Fields
                  e. Recommended Tags_
     c. If you are a seeker application
            i. _provide details on how to becknify a BAP application, explain this through a story
            ii. explain about the diff API's they need to implement
            ii. explain about the L2 config which needs to be applied
            iV. Integration testing using sandbox
            V. Integration testing using an actual Provider platform_
      d. If you are a provider application
            i. _provide details on how to becknify a BPP application, explain this through a story
            ii. explain about the diff API's they need to implement
            ii. explain about the L2 config which needs to be applied
            iV. Integration testing using sandbox
            V. Integration testing using an actual Provider platform_
      e. Learning Path

COMMUNITY
 a. MISSION Protocol Specifications Working Group - Mission Specific
b. Contribution Guide
c. Community Events - Mission Specific
d. Discussion Forum
e. Discord Community

HELP
 a. FAQ
b. Glossary
            
## Goals

- [ ] Build a starter kit that includes implementation guide
- [ ] The starter kit will cover both generic details and mission specific implementation details

## Expected Outcome

To have a start kit documentation which can be utilised by the global missions team across missions

**Comment by vbabuEM** [comment]
One version of this was reviewed on Tuesday. The following are the review comments:
1. Separate static sections and mission specific sections, so that it will be easy to modify during missions
2. Cite ONest in references section
3. Write stories for Seeker Journey and Provider Journey
4. Add samples for each artefact specific to missions 
cc @faizmagic

**Comment by faizmagic** [comment]
@vbabuEM , i have updated the description and TOC, please have a look. in most cases it is picked up from the ONEST starter kit, but i fine tuned the beckn implementation section. this section covers the implementation guide. other section are more for gyan.

**Comment by vbabuEM** [comment]
https://fide-official.atlassian.net/wiki/spaces/TPP/pages/494108721/Setting+up+a+new+Open+Network+using+Beckn

cc @faizmagic . We can go over this tomorrow.

**Comment by vbabuEM** [comment]
This task has been reviewed by Faiz. Marking this issue as done. Any changes will be part of another issue.

**Comment by vbabuEM** [comment]
The following is the location of the Starter Kit
https://fide-official.atlassian.net/wiki/x/MYBzHQ
