### ISSUE TITLE
Comprehensive Starter Kit - V2.0

### ISSUE THREAD

**Issue by viraj89** [beckn/missions#71]
## Description

As part of the previous iteration, we had created a Common Starter Kit for all missions. 
https://github.com/beckn/missions/issues/45
This document was reviewed and it had many comments. It was suggested that we should have a new starter kit with a different table of contents. 
Refer to the review comments in the issue above. 

This issue is to write a new starter kit with the suggested TOC.

**Comment by vbabuEM** [comment]
This work was delivered in multiple issues. They are listed below:
https://github.com/beckn/missions/issues/58
https://github.com/beckn/missions/issues/59
https://github.com/beckn/missions/issues/60
https://github.com/beckn/missions/issues/61

**Comment by vbabuEM** [comment]
Its been over month and half of sending it for review. Closing this. Any review comments can be written a separate issue.
