### ISSUE TITLE
Review and Update Beckn FAQ - Answer Unresolved Questions and Sync with GitHub FAQ File

### ISSUE THREAD

**Issue by viraj89** [beckn/missions#76]
## **Description**
There are several open questions on the Confluence page that are currently unanswered. These questions were raised during community calls, meetings, etc. The goal is to review these questions, provide clear answers, and then update the existing FAQ file in the GitHub repository. The work needs to be carried out in two stages:

1. **Stage 1**: Answer the unanswered questions directly on the Confluence page.
2. **Stage 2**: Sync the Confluence FAQ content with the markdown file on the GitHub repository.

### **Steps to Follow**:
1. **Review Unanswered Questions**:
   - Navigate to the Confluence page containing the open questions: [Beckn FAQs on Confluence](https://fide-official.atlassian.net/wiki/spaces/TPP/pages/510754836/Beckn+FAQ+s).
   - Identify and list down all unanswered or partially answered questions.

2. **Answer the Questions**:
   - Provide clear, concise, and accurate answers to each of the identified questions on the Confluence page.
   - Ensure that the answers are aligned with the latest information and guidelines related to the Beckn protocol.

3. **Update the GitHub FAQ File**:
   - Once the questions are answered on Confluence, update the corresponding markdown FAQ file located here: [Beckn FAQ on GitHub](https://github.com/beckn/missions/blob/main/docs/faq.md).
   - Ensure that the markdown file reflects all the updates made on the Confluence page.
   - Maintain the structure and format of the markdown file for consistency.

4. **Cross-reference**:
   - Ensure that the FAQ content is consistent across both the Confluence page and the GitHub markdown file.
   - Add any new insights or clarifications that emerged during the answering process.

### **Documentation Requirements**:
The updated FAQs need to be documented in both the Confluence page and the GitHub markdown file, ensuring consistency and completeness.

### **1. Review and Identify Open Questions**:
   - [ ] Access the Confluence page: [Beckn FAQs on Confluence](https://fide-official.atlassian.net/wiki/spaces/TPP/pages/510754836/Beckn+FAQ+s).
   - [ ] List all unanswered or partially answered questions.
   - [ ] Categorize the questions, if necessary, based on their relevance to specific topics within Beckn.

### **2. Provide Answers on Confluence**:
   - [ ] Research and gather necessary information to answer the questions.
   - [ ] Provide clear and accurate answers directly on the Confluence page.
   - [ ] Ensure that the answers are understandable and useful for the community.

### **3. Sync with GitHub FAQ File**:
   - [ ] Update the markdown FAQ file on GitHub with the new answers provided on Confluence.
   - [ ] Ensure the format and structure of the FAQ markdown file is maintained for consistency.
   - [ ] Check that all new information is reflected accurately.

### **4. Review and Cross-Reference**:
   - [ ] Double-check that the information is consistent across both Confluence and GitHub.
   - [ ] Address any discrepancies or additional questions that may arise during the review.
   - [ ] Ensure that both resources (Confluence and GitHub) are up-to-date with the latest FAQs.

## **Expected Outcome**:
The Beckn FAQ section on both Confluence and GitHub will be fully updated, providing clear, accurate, and helpful answers to all questions raised by the community. This will ensure consistency and accessibility of information across both platforms.

**Comment by vbabuEM** [comment]
I have moved and answered all the questions we had [here](https://fide-official.atlassian.net/wiki/spaces/TPP/pages/510754836/Beckn+FAQ+s) into the [FAQ document on the repository](https://github.com/beckn/missions/blob/main/docs/faq.md). This will be a living document. Everytime we get questions in the Open Office or in discord channels, we can keep updating this. Closing this for now.

**Comment by vbabuEM** [comment]
By the way to keep single source of truth, I have requested Faiz to remove the confluence version.

**Comment by vbabuEM** [comment]
The following is the link to the final deliverable for this ticket

https://github.com/beckn/missions/blob/main/docs/faq.md
