### ISSUE TITLE
VISTAAR: Create Implementation guide Vistaar

### ISSUE THREAD

**Issue by faizmagic** [beckn/missions#8]
### Description:
Now that we have a template starter kit and implementation guide, the following has been decided:

1. Missions team will create and maintain the implementation guide for each mission.
2. The implementation guide will be stored in this repo.
3. The only input for the implementation guide from outside will be the outcome visualization.
4. The implementation guide will have the following sections:
   a. Outcome visualization (received from the Program management team)
   b. Flow diagram
   c. API details
   d. Taxonomy and any Layer 2 rules
   e. General instructions for Seeker and Provider Platform implementers (this will mostly be common for all missions)
   f. Attachments (Postman collection and Layer 2 configuration file)

Following this approach, create the implementation guide for the VISTAAR project and share on Confluence Page [here](https://fide-official.atlassian.net/wiki/spaces/TPP/pages/399441921/VISTAAR). 

### Goals:
- [ ] Develop and maintain the VISTAAR implementation guide.
- [ ] Ensure all necessary sections are included and documented.
- [ ] Store the implementation guide in the specified repository.

### Expected Outcome:
- A comprehensive VISTAAR implementation guide is created and stored in the repository.
- The guide includes all required sections and is ready for use by mission teams and implementers.

### Acceptance Criteria:
- [ ] Implementation guide includes outcome visualization, flow diagram, API details, taxonomy, Layer 2 rules, and general instructions.
- [ ] Attachments (Postman collection and Layer 2 configuration file) are included.
- [ ] Implementation guide is reviewed and approved by relevant stakeholders.

### Mockups / Wireframes:
NA

### Product Name:
Beckn

### Domain:
AgriNet

### Tech Skills Needed:
Documentation, API Design, Process Flow

### Complexity:
High

### Category:
Documentation

### Sub Category:
Implementation Guide

**Comment by faizmagic** [comment]
@vbabuEM, In the VISTAAAR implementation guide, what is the recommendation we are providing if a BAP wants to download full set of catalogs or a BPP wants to expose the same.also if the catalogs are too huge, will the catalogs be delivered through a pagination

**Comment by vbabuEM** [comment]
@ravi-prakash-v , On the twin issues of catalog download/pagination, I went through the Protocol Spec discussions and could find two of them. 
https://github.com/beckn/protocol-specifications/discussions/127
https://github.com/beckn/protocol-specifications/discussions/328

I could not find a final recommended solution in either.
Given this, what is the recommended approach for these two cases:
a. Support for pagination when number of items in search result is high.
b. Recommended approach to fetch catalog when BAP wants to cache it for performance.

https://github.com/beckn/missions/issues/8

**Comment by vbabuEM** [comment]
2024-07-31
I will keep this open for one more day. Any more comments, I will incorporate. Then I will move the search/pagination to a new issue and close this.

**Comment by vbabuEM** [comment]
The first version has been available since August and filed here
https://github.com/beckn/missions/blob/main/VISTAAR/implementation_guide_knowledge_advisory.md
