### ISSUE TITLE
UEI EV Charging Implementation guide - Version 1.1

### ISSUE THREAD

**Issue by vbabuEM** [beckn/missions#85]
The UEI EV Charging Implementation guide needs the following changes:
1. Add missing annotations for the messages
2. Remove company names 
3. Fix some issues in response formats
4. Add versioning information to the readme as well as the guide

**Comment by vbabuEM** [comment]
The Global Programs team is working with the participants to come up with a common document on the various taxonomies currently used by the participants. This will be used as input for further modifications for the implementation guide.

cc: @poojamanjooran @meenakshi2468 @faizmagic

**Comment by vbabuEM** [comment]
Some of the questions that need to be answered are:
1. How does payment work? Payment between users and providers belonging to different organizations

2. What are we transacting on Beckn - Booking a slot vs Charging itself - UEI implementation does reservation. 
3. Per-message standardization

Global Programs will organize a series of sessions(3-4) to sort out questions 2 and 3.

@poojamanjooran @faizmagic

**Comment by yesrag2309** [comment]
**Pending Action Items as of 06th Sep 2024**

1. @vbabuEM to update the implementation guide with annotations and change in payment flow suggested by @faizmagic .
2. @vbabuEM  to initiate the email with Pooja to update the outcome visualization with the existing NP flows.

**Comment by vbabuEM** [comment]
https://docs.google.com/document/d/1U2a_FVBkZNfzuqOj-qjNVp6NcjrPFi8Gia0DGNQG8CA/

**Comment by vbabuEM** [comment]
https://github.com/beckn/missions/pull/108

**Comment by vbabuEM** [comment]
The updated implementation guide is https://github.com/beckn/missions/blob/main/UEI/implementation_guide_charging.md

**Comment by yesrag2309** [comment]
UEI EV charging implementation guide is created and sent review to Ravi. Hence closing this card. Review and Rework is tracking under #130  card in Sep16-29 iteration.

@vbabuEM @viraj89 @faizmagic
