### ISSUE TITLE
Create Implementation guide for UEI

### ISSUE THREAD

**Issue by faizmagic** [beckn/missions#9]
Now that we have a template starter kit and implementation guide, the following has been decided

Missions team will create and maintain the implementation guide for each mission.
The implementation guide will be stored in this repo
The only input for the implementation guide from outside will be the outcome visualization
The implementation guide will have the following sections
a. Outcome visualisation (received from the Program management team)
b. Flow diagram
c. API details
d. Taxonomy and any Layer 2 rules
e. General instructions for Seeker and Provider Platform implementers (this will mostly be common for all missions)
f. Attachments (postman collection and layer 2 configuration file)
Following this approach, create the implementation guide for the UEI project.

Outcome visualisation doc, provided by global mission steam: https://fide-official.atlassian.net/wiki/external/NmEzY2M4NzMzYzAyNGU0ZWE3YmRhODhjY2FiMzFmYzg#Outcome-Visualization

Implementation guide  to cover the implementation of the following use-cases
1. DOFP for Charging Point / Station discovery
2. Discovery and confirmation of energy demand 
3. Discovery and confirmation of green energy (energy stored in battery)

**Comment by vbabuEM** [comment]
https://github.com/beckn/missions/pull/46
