### ISSUE TITLE
Create core requirements for Beckn-ONIX Adapter

### ISSUE THREAD

**Issue by vbabuEM** [beckn/missions#95]
## Description

Rajaneesh is writing a core-spec for Beckn ONIX. Towards that we need to identify the core specs identified by the current implementation. This consists of two issues. This one for the Protocol Server and one more for Registry/Gateway. 

- This will be part of the Beckn-Onix spec version 1.0

**Comment by vbabuEM** [comment]
@rajaneeshk90  has sent this for review to Ravi and Binu & Tanya from ONDC (Binu has added some comments and those have been resolved). The review request has been sent on Sep 6.

**Comment by yesrag2309** [comment]
Document is created and sent review to Ravi. Hence closing this card. Review and Rework is tracking under #125 card in Sep16-29 iteration.

@vbabuEM @viraj89 @faizmagic
