### ISSUE TITLE
Beckn-Onix spec version 1.0

### ISSUE THREAD

**Issue by viraj89** [beckn/missions#99]
### Linked issues 
[#95 Create core requirements for Beckn-ONIX Adapter](https://github.com/beckn/missions/issues/95)
[#96 Create core requirements for Registry/Gateway](https://github.com/beckn/missions/issues/96)

**Comment by vbabuEM** [comment]
The Beckn-ONIX spec is being written by @rajaneeshk90 . These two sections are chapters in that spec.

**Comment by vbabuEM** [comment]
@rajaneeshk90  has sent this for review to Ravi and Binu & Tanya from ONDC (Binu has added some comments and those have been resolved). The review request has been sent on Sep 6. 
The deliverable for this is part of the document here: https://docs.google.com/document/d/1JlE-JTgQCPVPtFUqs3dIfBma3Koi_pVsO4LwB4hGcM8/edit#heading=h.m1mzlygez2v3

**Comment by yesrag2309** [comment]
Document is created and sent review to Ravi. Hence closing this card. Review and Rework is tracking under #127  card in Sep16-29 iteration.

@vbabuEM @viraj89 @faizmagic
